version: '3.1'

services:

  geekvk:
    image: mariadb:10.5.6-focal
    ports:
      - 127.0.0.1:3309:3306
    restart: always
    environment:
        MYSQL_USER: root
        MYSQL_DATABASE: geekvk
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    networks:
      geekbrains:

networks:
  geekbrains:
    driver: bridge
